classes:
  - kapitan.kube
  - kapitan.generators.kubernetes
  - kapitan.generators.terraform


parameters:
  scripts: []
  manifests: []
  docs:
    - templates/docs/README.md
  kapitan:
    compile:
      - output_path: docs
        input_type: jinja2
        input_paths: ${docs}
      - output_path: scripts
        input_type: jinja2
        input_paths: ${scripts}
      - output_path: manifests
        input_type: jsonnet
        output_type: yml
        input_paths: ${manifests}
    vars:
      target: ${target_name}

