{% set component = input_params %}
{% import 'templates/labels.j2' as labels with context  -%}
apiVersion: v1
kind: Service
metadata:
  name: {{ component.name }}
  namespace: {{ component.namespace }}
  labels:
    {{ labels.common(component) | indent(4)  }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
