---
name: Docker Build and Push
run-name: Docker Build for ${{ github.actor }} on branch ${{ github.ref_name }}

# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.ref_name }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows:
      - Python Tests
    types:
      - completed

jobs:
  build:
    # Only starts if Python tests were successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kapitan recursively
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      # Setup QEMU and Buildx to build multi-platform image
      # This was inspired by this example : https://docs.docker.com/build/ci/github-actions/examples/#multi-platform-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME}}
        if: env.DOCKERHUB_USERNAME != null
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME}}
        if: env.DOCKERHUB_USERNAME != null
        with:
          # list of Docker images to use as base name for tags
          images: |
            name=${{ env.DOCKERHUB_USERNAME }}/kapitan,enable=${{env.DOCKERHUB_USERNAME != null}}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha


      # Build both architectures but does not push, to allow for testing
      - name: build Kapitan Image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: False 
          file: Dockerfile
          tags: local-cache
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Builds again (caching is enabled) and load one platform to allow testing
      - name: build Kapitan Image
        uses: docker/build-push-action@v4
        with:
          push: False 
          file: Dockerfile
          tags: local-test
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Kapitan
        run: |
          docker run -t --rm local-test --version


      # Finally can push
      - name: Push Kapitan Image
        uses: docker/build-push-action@v4
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME}}
        if: env.DOCKERHUB_USERNAME != null
        with:
          platforms: linux/amd64,linux/arm64
          push: True
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max