---
name: Build and deploy documentation on merge to master
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'requirements.docs.txt'
      - 'mkdocs.yml'
      - 'CNAME'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kapitan recursively
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: ./mkdocs.yml
          REQUIREMENTS: requirements.docs.txt
