---
name: Python Lint

on:
  workflow_run:
    # Starts at the same time as Python Tests
    workflows:
      - Python Tests
    types:
      - requested
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@main
