---
name: Python Lint
on: 
  push:
    paths-ignore:
      - 'docs/**'
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@main
